@baseurl=http://localhost:4000
@userAgent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36
@authToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJ0YWt1bWlAZW1hbnRsZS5uZXQiLCJuYW1lIjoidGFrdW1pIiwiaWF0IjoxNTk0MzMwMTYyLCJleHAiOjE1OTQzMzczNjJ9.kPG7QNc4nK7BaFmCZCIkA3Lmw8veAM_sTCoYh0sbIXQ

###
# Pokemon query
POST {{baseurl}}/graphql  HTTP/1.1
authorization: {{authToken}}
content-type: application/json
User-Agent: {{userAgent}}

{"query":"query getPoke {\n  pokemon(pokemonNo: 150) {\n    name\n    height\n    weight\n    types {\n      slot\n      type {\n        name\n        url\n      }\n    }\n  }\n}\n"}


###
# Login
POST {{baseurl}}/graphql  HTTP/1.1
content-type: application/json

{"query":"mutation Login {\n  login(user: {email: \"yumiko@emantle.net\", password: \"yumiko\"}) {\n    token\n    user {\n      name\n      id\n    }\n  }\n}\n"}
