@baseurl=http://localhost:4000
@userAgent=Mozilla
@authToken=xxx.xxx.xxx-xxx

###
# Pokemon query
POST {{baseurl}}/graphql  HTTP/1.1
authorization: {{authToken}}
content-type: application/json
User-Agent: {{userAgent}}

{"query":"query getPoke {\n  pokemon(pokemonNo: 150) {\n    name\n    height\n    weight\n    types {\n      slot\n      type {\n        name\n        url\n      }\n    }\n  }\n}\n"}


###
# Login
POST {{baseurl}}/graphql  HTTP/1.1
content-type: application/json

{"query":"mutation Login {\n  login(user: {email: \"xxx@yyy.zzz\", password: \"xxx\"}) {\n    token\n    user {\n      name\n      id\n    }\n  }\n}\n"}
